server:
  port: 9002
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  sql:
    init:
      mode: always
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/church_registration
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  application:
    name: registration-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
      fail-fast: false
